## Numpy
    - Numpy 배열 생성
    - Numpy 배열 인덱싱
    - Numpy 배열 슬라이싱
    - Boolean 인덱싱
    - Numpy 유니버셜 함수

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(type(arr), arr)

<class 'numpy.ndarray'> [1 2 3]


In [3]:
print(arr.shape)

(3,)


In [4]:
print(arr[0], arr[1], arr[2])

1 2 3


In [5]:
arr[0] = 5
arr

array([5, 2, 3])

In [6]:
arr2 = np.array( [[1,2,3],
                   [4,5,6]])

In [7]:
type(arr2), arr2, arr2.shape

(numpy.ndarray, array([[1, 2, 3],
        [4, 5, 6]]), (2, 3))

In [8]:
print(arr2[0,0], arr2[0,1], arr2[1,0])

1 2 4


In [9]:
arr3 = np.arange(32)
arr3, arr3.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]), (32,))

In [10]:
arr3.reshape(4,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [11]:
arr3.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

In [12]:
arr3.reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [13]:
a = np.zeros( (2,2) )
a

array([[0., 0.],
       [0., 0.]])

In [14]:
b = np.ones( (3,3) )
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
c = np.full((5,5), -1)
c

array([[-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1]])

In [16]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [17]:
e = np.random.random((2,2))
e

array([[0.5327099 , 0.05373102],
       [0.43546894, 0.84014243]])

In [18]:
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr, arr.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), (3, 4))

In [19]:
row_r1 = arr[1,:]
row_r1

array([5, 6, 7, 8])

In [20]:
row_r2 = arr[1:2, :]
row_r2

array([[5, 6, 7, 8]])

In [21]:
col_r1 = a[:, 1]
col_r1

array([0., 0.])

In [22]:
col_r2 = a[:, 1:2]
col_r2

array([[0.],
       [0.]])

In [23]:
arr = np.array( [[1,2], [3,4], [5,6]])
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
arr[[0,1,2], [0,1,0]]

array([1, 4, 5])

In [25]:
arr[0,0], arr[1,1], arr[2,0]

(1, 4, 5)

In [26]:
arr[[0,0], [1,1]]

array([2, 2])

In [27]:
arr[0,1], arr[0,1]

(2, 2)

In [28]:
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [29]:
arr2 = np.array([0,2,0,1])

In [30]:
arr[np.arange(4),arr2]

array([ 1,  6,  7, 11])

In [31]:
arr[np.arange(4), arr2] *= 10

In [32]:
arr

array([[ 10,   2,   3],
       [  4,   5,  60],
       [ 70,   8,   9],
       [ 10, 110,  12]])

In [33]:
arr = np.arange(1,13).reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
bool_idx = ( arr >= 5)
bool_idx

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [35]:
arr[bool_idx]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
arr[ [True,False,False,True] ]

array([[ 1,  2,  3],
       [10, 11, 12]])

In [37]:
arr[arr >= 10]

array([10, 11, 12])

In [38]:
arr1 = np.array([1,2])
arr1, arr1.dtype

(array([1, 2]), dtype('int32'))

In [39]:
arr2 = np.array([1.0,2.0])
arr2, arr2.dtype

(array([1., 2.]), dtype('float64'))

In [40]:
arr3 = np.array([1,2], dtype=np.int64)
arr3, arr3.dtype

(array([1, 2], dtype=int64), dtype('int64'))

In [41]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [42]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [43]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [44]:
print(x * y)
print(np.multiply(x, y))


[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [45]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [46]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [47]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])


In [48]:
v = np.array([9,10])
w = np.array([11, 12])


In [49]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [50]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [51]:
print(x.dot(y))
print(np.dot(x, y))


[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [52]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # 모든 요소를 합한 값을 연산; 출력 "10"
print(np.sum(x, axis=0))  # 각 열에 대한 합을 연산; 출력 "[4 6]"
print(np.sum(x, axis=1))  # 각 행에 대한 합을 연산; 출력 "[3 7]"


10
[4 6]
[3 7]


In [53]:
np.max(x)
np.max(x, axis=0)
np.max(x, axis=1)
np.argmax(x)
np.argmax(x,axis=0)
np.argmax(x,axis=1)

array([1, 1], dtype=int64)

In [54]:
np.mean(x)
np.mean(x,axis=0)
np.mean(x,axis=1)

array([1.5, 3.5])

In [55]:
x = np.array([[1,2], [3,4]])
print (x)

[[1 2]
 [3 4]]


In [56]:
print (x.T) 

[[1 3]
 [2 4]]


In [57]:
v = np.array([1,2,3])
print (v)    # 출력 "[1 2 3]"

[1 2 3]


In [58]:
print (v.T)  # 출력 "[1 2 3]"


[1 2 3]


In [59]:
import numpy as np

xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [60]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [61]:
result2 = np.where(cond, xarr, yarr)
print(result2)

[1.1 2.2 1.3 1.4 2.5]


In [62]:
arr = np.random.randn(4,4)
print(arr)

[[-1.46527429  0.25153427 -0.6494796   0.04048436]
 [ 0.23585605  1.74609646  1.54126638 -0.20686863]
 [ 0.17877694 -2.00819449 -0.99095384 -1.71247152]
 [ 0.69604508  0.8789213  -1.0336603   0.42259929]]


In [63]:
print(np.where(arr>0, 1, -1))

[[-1  1 -1  1]
 [ 1  1  1 -1]
 [ 1 -1 -1 -1]
 [ 1  1 -1  1]]


In [64]:
print(np.where(arr>0, 0, arr))


[[-1.46527429  0.         -0.6494796   0.        ]
 [ 0.          0.          0.         -0.20686863]
 [ 0.         -2.00819449 -0.99095384 -1.71247152]
 [ 0.          0.         -1.0336603   0.        ]]


In [65]:
samples = np.random.normal(size=(4,4))
print(samples)

[[ 1.56823466  1.39069061  0.49411295  1.64242237]
 [ 1.25195332 -0.42887929 -1.31106805 -0.37865349]
 [-1.14031751 -0.24456678  1.15101152  0.71587942]
 [-1.39869471 -0.26849317  1.30438659 -1.01841734]]


In [66]:
from random import normalvariate 
N = 1000000

In [67]:
%timeit samples = [normalvariate(0,1) for _ in range(N)]

1.17 s ± 37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [68]:
import numpy as np
%timeit np.random.normal(size=N)

42.7 ms ± 278 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Pandas
    - Series 생성 및 접근
    - DataFrame 생성 및 접근
    - DataFrame 속성 및 함수
    - DataFrame 데이터 접근
        - 인덱싱
        - 슬라이싱
        - loc, iloc, at, iat
        - Boolean 인덱싱
    - DataFrame 행, 열 삭제

In [69]:
import pandas as pd
import numpy as np

In [70]:
object1 = pd.Series( [4, 5, -3, 6])
object1

0    4
1    5
2   -3
3    6
dtype: int64

In [71]:
object2 = pd.Series([4,5,-3,6] ,index=['d','a','c','b'])
object2

d    4
a    5
c   -3
b    6
dtype: int64

In [72]:
object2[['a','d']]

a    5
d    4
dtype: int64

In [73]:
object2[object2 > 0]

d    4
a    5
b    6
dtype: int64

In [74]:
data = {
    'state': ['oh','oh','oh','Nev','Nev'],
    'year': [2000,2001,2002,2001,2002],
    'population':[1.5,1.7,2.3,2.9,3.2]
}

In [75]:
data

{'state': ['oh', 'oh', 'oh', 'Nev', 'Nev'],
 'year': [2000, 2001, 2002, 2001, 2002],
 'population': [1.5, 1.7, 2.3, 2.9, 3.2]}

In [76]:
dataframe = pd.DataFrame(data)
dataframe

state  year  population
0    oh  2000         1.5
1    oh  2001         1.7
2    oh  2002         2.3
3   Nev  2001         2.9
4   Nev  2002         3.2

In [77]:
pd.DataFrame(data, columns=['year', 'state', 'population'])

year state  population
0  2000    oh         1.5
1  2001    oh         1.7
2  2002    oh         2.3
3  2001   Nev         2.9
4  2002   Nev         3.2

In [78]:
dataframe2 = pd.DataFrame(data, columns=['year', 'state', 'population','debt'],
                      index=['one','two','three','four','five'])
dataframe2

year state  population debt
one    2000    oh         1.5  NaN
two    2001    oh         1.7  NaN
three  2002    oh         2.3  NaN
four   2001   Nev         2.9  NaN
five   2002   Nev         3.2  NaN

In [79]:
s1 = pd.Series([1,3,5,np.nan,6,8])
s1

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [80]:
dates = pd.date_range('20200101', periods=6)
dates

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

In [81]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2020-01-01 -0.116334 -1.378891 -0.911693  0.292370
2020-01-02  2.174608  1.085896 -0.045779 -1.027386
2020-01-03 -0.912432  1.708224  0.033328  1.768449
2020-01-04 -0.347098 -0.269184 -0.154387  0.651759
2020-01-05 -0.076795 -1.742529 -0.953407  0.722631
2020-01-06  0.535323  0.228241 -1.833861  0.086227

In [82]:
df2 = pd.DataFrame({
    'A':1.,
    'B':pd.Timestamp('20200101'),
    'C':pd.Series(1,index=list(range(4)),dtype='float32'),
    'D':np.array([3]*4,dtype='int32'),
    'E':pd.Categorical(["test","train","test","train"]),
    'F':'foo'
})

df2

A          B    C  D      E    F
0  1.0 2020-01-01  1.0  3   test  foo
1  1.0 2020-01-01  1.0  3  train  foo
2  1.0 2020-01-01  1.0  3   test  foo
3  1.0 2020-01-01  1.0  3  train  foo

In [83]:
df.head()

A         B         C         D
2020-01-01 -0.116334 -1.378891 -0.911693  0.292370
2020-01-02  2.174608  1.085896 -0.045779 -1.027386
2020-01-03 -0.912432  1.708224  0.033328  1.768449
2020-01-04 -0.347098 -0.269184 -0.154387  0.651759
2020-01-05 -0.076795 -1.742529 -0.953407  0.722631

In [84]:
df.tail()

A         B         C         D
2020-01-02  2.174608  1.085896 -0.045779 -1.027386
2020-01-03 -0.912432  1.708224  0.033328  1.768449
2020-01-04 -0.347098 -0.269184 -0.154387  0.651759
2020-01-05 -0.076795 -1.742529 -0.953407  0.722631
2020-01-06  0.535323  0.228241 -1.833861  0.086227

In [85]:
df.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

In [86]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [87]:
df.values

array([[-0.11633402, -1.37889107, -0.91169268,  0.29237023],
       [ 2.1746082 ,  1.08589649, -0.04577933, -1.0273857 ],
       [-0.91243159,  1.70822407,  0.03332837,  1.76844933],
       [-0.3470982 , -0.26918368, -0.15438653,  0.65175865],
       [-0.07679485, -1.74252934, -0.95340721,  0.72263146],
       [ 0.53532322,  0.22824141, -1.83386098,  0.08622728]])

In [88]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.209545 -0.061374 -0.644300  0.415675
std    1.069998  1.351806  0.726571  0.914999
min   -0.912432 -1.742529 -1.833861 -1.027386
25%   -0.289407 -1.101464 -0.942979  0.137763
50%   -0.096564 -0.020471 -0.533040  0.472064
75%    0.382294  0.871483 -0.072931  0.704913
max    2.174608  1.708224  0.033328  1.768449

In [89]:
df.T

2020-01-01  2020-01-02  2020-01-03  2020-01-04  2020-01-05  2020-01-06
A   -0.116334    2.174608   -0.912432   -0.347098   -0.076795    0.535323
B   -1.378891    1.085896    1.708224   -0.269184   -1.742529    0.228241
C   -0.911693   -0.045779    0.033328   -0.154387   -0.953407   -1.833861
D    0.292370   -1.027386    1.768449    0.651759    0.722631    0.086227

In [90]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2020-01-01  0.292370 -0.911693 -1.378891 -0.116334
2020-01-02 -1.027386 -0.045779  1.085896  2.174608
2020-01-03  1.768449  0.033328  1.708224 -0.912432
2020-01-04  0.651759 -0.154387 -0.269184 -0.347098
2020-01-05  0.722631 -0.953407 -1.742529 -0.076795
2020-01-06  0.086227 -1.833861  0.228241  0.535323

In [91]:
df.sort_index(axis=1)

A         B         C         D
2020-01-01 -0.116334 -1.378891 -0.911693  0.292370
2020-01-02  2.174608  1.085896 -0.045779 -1.027386
2020-01-03 -0.912432  1.708224  0.033328  1.768449
2020-01-04 -0.347098 -0.269184 -0.154387  0.651759
2020-01-05 -0.076795 -1.742529 -0.953407  0.722631
2020-01-06  0.535323  0.228241 -1.833861  0.086227

In [92]:
df.sort_values(by='B')

A         B         C         D
2020-01-05 -0.076795 -1.742529 -0.953407  0.722631
2020-01-01 -0.116334 -1.378891 -0.911693  0.292370
2020-01-04 -0.347098 -0.269184 -0.154387  0.651759
2020-01-06  0.535323  0.228241 -1.833861  0.086227
2020-01-02  2.174608  1.085896 -0.045779 -1.027386
2020-01-03 -0.912432  1.708224  0.033328  1.768449

In [93]:
dates = pd.date_range('1/1/2020', periods=5)
df = pd.DataFrame(np.random.randn(5,4), index=dates, columns=['A','B','C','D'])
df

A         B         C         D
2020-01-01 -1.410451  0.336613  0.155979  0.864045
2020-01-02 -0.244826  0.487656 -0.864290  1.512732
2020-01-03  0.787005 -0.042736  1.457315  0.225014
2020-01-04 -0.727673  0.666490  0.107338  0.315625
2020-01-05 -1.298244 -1.524954 -0.513073  0.333332

In [94]:
s = df['A']
s[dates[3]]

-0.7276726940724378

In [95]:
df

A         B         C         D
2020-01-01 -1.410451  0.336613  0.155979  0.864045
2020-01-02 -0.244826  0.487656 -0.864290  1.512732
2020-01-03  0.787005 -0.042736  1.457315  0.225014
2020-01-04 -0.727673  0.666490  0.107338  0.315625
2020-01-05 -1.298244 -1.524954 -0.513073  0.333332

In [96]:
df[['B','A']] = df[['A','B']]
df

A         B         C         D
2020-01-01  0.336613 -1.410451  0.155979  0.864045
2020-01-02  0.487656 -0.244826 -0.864290  1.512732
2020-01-03 -0.042736  0.787005  1.457315  0.225014
2020-01-04  0.666490 -0.727673  0.107338  0.315625
2020-01-05 -1.524954 -1.298244 -0.513073  0.333332

In [97]:
df[['A','B']]

A         B
2020-01-01  0.336613 -1.410451
2020-01-02  0.487656 -0.244826
2020-01-03 -0.042736  0.787005
2020-01-04  0.666490 -0.727673
2020-01-05 -1.524954 -1.298244

In [98]:
df.loc[:,['B','A']] = df[['A','B']]

In [99]:
df.loc[:,['B','A']] = df[['A','B']].values

In [100]:
df[['A','B']]

A         B
2020-01-01 -1.410451  0.336613
2020-01-02 -0.244826  0.487656
2020-01-03  0.787005 -0.042736
2020-01-04 -0.727673  0.666490
2020-01-05 -1.298244 -1.524954

In [101]:
df['A']

2020-01-01   -1.410451
2020-01-02   -0.244826
2020-01-03    0.787005
2020-01-04   -0.727673
2020-01-05   -1.298244
Freq: D, Name: A, dtype: float64

In [102]:
df[0:3]

A         B         C         D
2020-01-01 -1.410451  0.336613  0.155979  0.864045
2020-01-02 -0.244826  0.487656 -0.864290  1.512732
2020-01-03  0.787005 -0.042736  1.457315  0.225014

In [103]:
df['20200101':'20200103']

A         B         C         D
2020-01-01 -1.410451  0.336613  0.155979  0.864045
2020-01-02 -0.244826  0.487656 -0.864290  1.512732
2020-01-03  0.787005 -0.042736  1.457315  0.225014

In [104]:
df.loc[dates[0]]

A   -1.410451
B    0.336613
C    0.155979
D    0.864045
Name: 2020-01-01 00:00:00, dtype: float64

In [105]:
df.loc[:, ['A','B']]

A         B
2020-01-01 -1.410451  0.336613
2020-01-02 -0.244826  0.487656
2020-01-03  0.787005 -0.042736
2020-01-04 -0.727673  0.666490
2020-01-05 -1.298244 -1.524954

In [106]:
df.loc['20200101':'20200103', ['A','B']]

A         B
2020-01-01 -1.410451  0.336613
2020-01-02 -0.244826  0.487656
2020-01-03  0.787005 -0.042736

In [107]:
df.loc[dates[0], 'A']

-1.4104505711190805

In [108]:
df.at[dates[0], 'A']

-1.4104505711190805

In [109]:
df.iloc[3]

A   -0.727673
B    0.666490
C    0.107338
D    0.315625
Name: 2020-01-04 00:00:00, dtype: float64

In [110]:
df.iloc[3:5, 0:2]

A         B
2020-01-04 -0.727673  0.666490
2020-01-05 -1.298244 -1.524954

In [111]:
df.iloc[[1,2,4], [0,2]]

A         C
2020-01-02 -0.244826 -0.864290
2020-01-03  0.787005  1.457315
2020-01-05 -1.298244 -0.513073

In [112]:
df.iloc[1:3, :]

A         B         C         D
2020-01-02 -0.244826  0.487656 -0.864290  1.512732
2020-01-03  0.787005 -0.042736  1.457315  0.225014

In [113]:
df.iloc[:, 1:3]

B         C
2020-01-01  0.336613  0.155979
2020-01-02  0.487656 -0.864290
2020-01-03 -0.042736  1.457315
2020-01-04  0.666490  0.107338
2020-01-05 -1.524954 -0.513073

In [114]:
df.iloc[1, 1]

0.4876558435940499

In [115]:
%timeit df.loc["20200101", "A"]

420 µs ± 3.88 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [116]:
%timeit df.at["20200101", "A"]

174 µs ± 4.78 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [117]:
%timeit df.iloc[0, 0]

9.96 µs ± 643 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [118]:
%timeit df.iat[0, 0]

6.35 µs ± 464 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [119]:
df[df['A'] > 0]

A         B         C         D
2020-01-03  0.787005 -0.042736  1.457315  0.225014

In [120]:
df[df > 0]

A         B         C         D
2020-01-01       NaN  0.336613  0.155979  0.864045
2020-01-02       NaN  0.487656       NaN  1.512732
2020-01-03  0.787005       NaN  1.457315  0.225014
2020-01-04       NaN  0.666490  0.107338  0.315625
2020-01-05       NaN       NaN       NaN  0.333332

In [121]:
df2 = df.copy()

In [137]:
df2['E'] = ['one', 'one', 'two', 'three', 'four']
df2

A         B         C         D      E
2020-01-01 -1.410451 -0.336613 -0.155979 -0.864045    one
2020-01-02 -0.244826 -0.487656 -0.864290 -1.512732    one
2020-01-03 -0.787005 -0.042736 -1.457315 -0.225014    two
2020-01-04 -0.727673 -0.666490 -0.107338 -0.315625  three
2020-01-05 -1.298244 -1.524954 -0.513073 -0.333332   four

In [141]:
# df2[df2['E'].isin(['two','four'])]
df2['E'].isin(['two','four'])

2020-01-01    False
2020-01-02    False
2020-01-03     True
2020-01-04    False
2020-01-05     True
Freq: D, Name: E, dtype: bool

In [146]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [147]:
df2['F'] = s1
df2

A         B         C         D      E   F
2020-01-01 -1.410451 -0.336613 -0.155979 -0.864045    one NaN
2020-01-02 -0.244826 -0.487656 -0.864290 -1.512732    one NaN
2020-01-03 -0.787005 -0.042736 -1.457315 -0.225014    two NaN
2020-01-04 -0.727673 -0.666490 -0.107338 -0.315625  three NaN
2020-01-05 -1.298244 -1.524954 -0.513073 -0.333332   four NaN

In [126]:
df2.at[dates[0], 'A'] = 0
df2

A         B         C         D      E  F
2020-01-01  0.000000  0.336613  0.155979  0.864045    one  1
2020-01-02 -0.244826  0.487656 -0.864290  1.512732    one  2
2020-01-03  0.787005 -0.042736  1.457315  0.225014    two  3
2020-01-04 -0.727673  0.666490  0.107338  0.315625  three  4
2020-01-05 -1.298244 -1.524954 -0.513073  0.333332   four  5

In [127]:
df2.iat[0, 1] = 0
df2

A         B         C         D      E  F
2020-01-01  0.000000  0.000000  0.155979  0.864045    one  1
2020-01-02 -0.244826  0.487656 -0.864290  1.512732    one  2
2020-01-03  0.787005 -0.042736  1.457315  0.225014    two  3
2020-01-04 -0.727673  0.666490  0.107338  0.315625  three  4
2020-01-05 -1.298244 -1.524954 -0.513073  0.333332   four  5

In [128]:
df2.loc[:, 'D'] = np.array([5]*len(df2))
df2

A         B         C  D      E  F
2020-01-01  0.000000  0.000000  0.155979  5    one  1
2020-01-02 -0.244826  0.487656 -0.864290  5    one  2
2020-01-03  0.787005 -0.042736  1.457315  5    two  3
2020-01-04 -0.727673  0.666490  0.107338  5  three  4
2020-01-05 -1.298244 -1.524954 -0.513073  5   four  5

In [129]:
df2 = df.copy()
df2

A         B         C         D
2020-01-01 -1.410451  0.336613  0.155979  0.864045
2020-01-02 -0.244826  0.487656 -0.864290  1.512732
2020-01-03  0.787005 -0.042736  1.457315  0.225014
2020-01-04 -0.727673  0.666490  0.107338  0.315625
2020-01-05 -1.298244 -1.524954 -0.513073  0.333332

In [130]:
df2[df2 > 0] = -df2
df2

A         B         C         D
2020-01-01 -1.410451 -0.336613 -0.155979 -0.864045
2020-01-02 -0.244826 -0.487656 -0.864290 -1.512732
2020-01-03 -0.787005 -0.042736 -1.457315 -0.225014
2020-01-04 -0.727673 -0.666490 -0.107338 -0.315625
2020-01-05 -1.298244 -1.524954 -0.513073 -0.333332

In [131]:
df3 = df.copy()
df3

A         B         C         D
2020-01-01 -1.410451  0.336613  0.155979  0.864045
2020-01-02 -0.244826  0.487656 -0.864290  1.512732
2020-01-03  0.787005 -0.042736  1.457315  0.225014
2020-01-04 -0.727673  0.666490  0.107338  0.315625
2020-01-05 -1.298244 -1.524954 -0.513073  0.333332

In [151]:
df3 = df3.where(df3 <= 0, -df3)
df3

A         B         C         D
2020-01-02 -0.244826 -0.487656 -0.864290 -1.512732
2020-01-03 -0.787005 -0.042736 -1.457315 -0.225014
2020-01-04 -0.727673 -0.666490 -0.107338 -0.315625
2020-01-05 -1.298244 -1.524954 -0.513073 -0.333332

In [133]:
df3.drop(df3.index[0], inplace=True)
df3

A         B         C         D
2020-01-02 -0.244826 -0.487656 -0.864290 -1.512732
2020-01-03 -0.787005 -0.042736 -1.457315 -0.225014
2020-01-04 -0.727673 -0.666490 -0.107338 -0.315625
2020-01-05 -1.298244 -1.524954 -0.513073 -0.333332

In [156]:
df3.drop(['A'], axis=1)

B         C         D
2020-01-02 -0.487656 -0.864290 -1.512732
2020-01-03 -0.042736 -1.457315 -0.225014
2020-01-04 -0.666490 -0.107338 -0.315625
2020-01-05 -1.524954 -0.513073 -0.333332